var mysql_dbc = require('../../mysql/db_con.js')();
var connection = mysql_dbc.init();

var Exam = {

	hstList : function(examSeq, begin, size, callback) {
		
		return connection.query("SELECT * FROM (SELECT " +
				"(SELECT NAME FROM SCHEDULE WHERE SEQ = P.SCHEDULE_SEQ AND SEQ = A.SCHEDULE_SEQ) AS SCHEDULE_NAME, " +
				"(SELECT NAME FROM DEPARTMENT WHERE SEQ = (SELECT DEPARTMENT_SEQ FROM USER WHERE SEQ = A.USER_SEQ)) AS DEPARTMENT, " +
				"(SELECT NAME FROM POSITION WHERE SEQ = (SELECT POSITION_SEQ FROM USER WHERE SEQ = A.USER_SEQ)) AS POSITION, " +
				"(SELECT NAME FROM USER WHERE SEQ = A.USER_SEQ) AS USER_NAME " +
				"FROM APPLY A INNER JOIN PERIOD P ON A.PERIOD_SEQ = P.SEQ " +
				"WHERE P.EXAM_SEQ = " + examSeq + " ORDER BY A.SEQ DESC) M " + 
				"LIMIT ?, ?", [begin, size], callback);
	}, 

	
	hstCount : function (examSeq, callback) {
		
		return connection.query("SELECT COUNT(*) AS CNT FROM (SELECT * FROM (SELECT " +
				"(SELECT NAME FROM SCHEDULE WHERE SEQ = P.SCHEDULE_SEQ AND SEQ = A.SCHEDULE_SEQ) AS SCHEDULE_NAME, " +
				"(SELECT NAME FROM DEPARTMENT WHERE SEQ = (SELECT DEPARTMENT_SEQ FROM USER WHERE SEQ = A.USER_SEQ)) AS DEPARTMENT, " +
				"(SELECT NAME FROM POSITION WHERE SEQ = (SELECT POSITION_SEQ FROM USER WHERE SEQ = A.USER_SEQ)) AS POSITION, " +
				"(SELECT NAME FROM USER WHERE SEQ = A.USER_SEQ) AS USER_NAME " +
				"FROM APPLY A INNER JOIN PERIOD P ON A.PERIOD_SEQ = P.SEQ " +
				"WHERE P.EXAM_SEQ = " + examSeq + " ORDER BY A.SEQ DESC)M)C", callback);
	},

	
};

module.exports = Exam; 
