var mysql_dbc = require('../../mysql/db_con.js')();
var connection = mysql_dbc.init();

var Main = {
	list : function (callback) {
		return connection.query(
			"SELECT PERIOD.SEQ, EXAM_SEQ, PERIOD.CLASS AS PERIOD_CLASS, EXAM_NAME, EXAM_SCHOOL, DEPARTMENT.NAME AS DEPARTMENT_NAME, USER.NAME, APPLY.CLASS AS USER_CLASS "+
			"FROM "+
			"(SELECT +" +
			"	P.SEQ AS SEQ, P.EXAM_SEQ AS EXAM_SEQ, P.CLASS AS CLASS, E.NAME AS EXAM_NAME, E.SCHOOL AS EXAM_SCHOOL, E.ADDR AS EXAM_ADDR " +
			"FROM PERIOD AS P LEFT JOIN EXAM AS E ON (P.EXAM_SEQ=E.SEQ),  "+
			"	(SELECT +" +
			"		MAX(SEQ) AS SCHEDULE_SEQ "+
			"	FROM SCHEDULE  "+
			"	WHERE APPLY_DATE <= NOW()) AS S "+
			"WHERE P.SCHEDULE_SEQ = S.SCHEDULE_SEQ) AS PERIOD "+
			"LEFT JOIN APPLY AS APPLY ON(PERIOD.SEQ=APPLY.PERIOD_SEQ AND PERIOD.CLASS=APPLY.CLASS) " +
			"LEFT JOIN USER AS USER ON(APPLY.USER_SEQ=USER.SEQ) "+
			"LEFT JOIN DEPARTMENT AS DEPARTMENT ON(USER.DEPARTMENT_SEQ=DEPARTMENT.SEQ) ", 
			callback);
	}
};

module.exports = Main; 
